nsqlookupd:
  image: nsqio/nsq
  ports:
    - "4160:4160"
    - "4161:4161"
  command: /nsqlookupd

nsqd:
  image: nsqio/nsq
  ports:
    - "4150"
    - "4151"
  links:
    - nsqlookupd:nsqlookupd
  command: /nsqd --lookupd-tcp-address=nsqlookupd:4160

nsqadmin:
  image: nsqio/nsq
  ports:
    - "4171:4171"
  links:
    - nsqlookupd:nsqlookupd
  command: /nsqadmin --lookupd-http-address=nsqlookupd:4161

redis:
  image: redis
  ports:
    - "6379:6379"

consul1:
  image: "progrium/consul:latest"
  container_name: "consul1"
  hostname: "consul1"
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53"
  command: "-server -bootstrap-expect 3 -ui-dir /ui"

consul2:
  image: "progrium/consul:latest"
  container_name: "consul2"
  hostname: "consul2"
  expose:
    - "8400"
    - "8500"
    - "8600"
  command: "-server -join consul1"
  depends_on:
    - consul1

consul3:
  image: "progrium/consul:latest"
  container_name: "consul3"
  hostname: "consul3"
  expose:
    - "8400"
    - "8500"
    - "8600"
  command: "-server -join consul1"
  depends_on:
    - consul1
